/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 roomof_room_test2.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/roomof_room_test2.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.397, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["podloga.002"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["sciana_okno.002"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["stolik.005"]}
        />
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.017"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/roomof_room_test2.gltf");
